language: objective-c
xcodebuild test -scheme Flipper \
				-configuration Debug \
                -sdk iphonesimulator \
                -verbose \
                -destination 'platform=iOS Simulator,name=iPad Air'